### ISSUE TITLE
Trouble installing npm

### ISSUE THREAD

**Issue by CristanteAM** [jehervy/node-virtual-gamepads#86] opened 2020-12-28 22:32 UTC
This is the output I received after trying to install npm. How to overcome this problem? (p.s.: I'm new to linux)

>mypc@mypc:~/node-virtual-gamepads$ npm install

ref@1.3.5 install /home/cristanteam/node-virtual-gamepads/node_modules/ref-array/node_modules/ref
node-gyp rebuild

Traceback (most recent call last):
  File "/usr/share/nodejs/node-gyp/gyp/gyp_main.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/cristanteam/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/home/cristanteam/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/home/cristanteam/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/cristanteam/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/home/cristanteam/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/cristanteam/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gyp==0.1' distribution was not found and is required by the application
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/nodejs/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-58-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/cristanteam/node-virtual-gamepads/node_modules/ref-array/node_modules/ref
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ref@1.3.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cristanteam/.npm/_logs/2020-12-28T22_14_45_016Z-debug.log

**Comment by robsdedude** [comment] 2020-12-28 23:33
Seems you're using node version 10. Note that the `README.md` states "This application is only tested with node version 9. 10 and 12 are known to cause trouble because of the dependencies."

However, the unstable version in the `develop` branch should work with Node 10 and 12. So either downgrade your Node version or checkout the develop branch and it should work.

I'll close the issue as I'm pretty confident that this is the cause of the error. If the problem persists, feel free to reopen it.

**Closed by robsdedude** 2020-12-28 23:33 UTC

**Comment by cpcbegin** [comment] 2021-05-25 20:28
I have the same problem using develop branch, my node version is v10.19.0
(Ubuntu Mate 20.04)
